[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
# These are made up endpoints for testing.
# We intentionally use both dashes and underscores to ensure both are supported.
mainnet = "https://mainnet-rpc.com"
optimism_goerli = "https://optimism_goerli-rpc.com"
arbitrum-one-goerli = "https://arbitrum_one_goerli-rpc.com"

[fmt]
# These are all the `forge fmt` defaults.
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
ignore = ["src/console.sol", "src/console2.sol"]